OneHundredBrews/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :beers do
	resources :reviews
  end
  root 'beers#index'
end

OneHundredBrews/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

OneHundredBrews/app/models/beer.rb
class Beer < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_many:reviews
	
	has_attached_file :beer_image, :styles => { :beer_index => "300x575^", :beer_show => "300x575^" }, :default_url => "/images/:style/missing.png"
	validates_attachment_content_type :beer_image, :content_type => /\Aimage\/.*\Z/
end

OneHundredBrews/app/models/category.rb
class Category < ApplicationRecord
	has_many :beers
end

OneHundredBrews/app/models/review.rb
class Review < ApplicationRecord
	belongs_to :beer
	belongs_to :user
end

OneHundredBrews/app/models/user.rb
class User < ApplicationRecord
	has_many :beers
	has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

OneHundredBrews/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

OneHundredBrews/app/controllers/beers_controller.rb
class BeersController < ApplicationController
	before_action :find_beer, only: [:show, :edit, :update, :destroy]
	
	
	def index
		if params[:category].blank?
			@beers = Beer.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
			@beers = Beer.where(:category_id => @category_id).order("created_at DESC")
		end
	end
	
	
	def show
		
	end
	
	
	def new
		@beer = current_user.beers.build
		@categories = Category.all.map{ |c| [c.name, c.id] }		
	end
	
	def create
		@beer = current_user.beers.build(beer_params)
		@beer.category_id = params[:category_id]
		
		if @beer.save
			redirect_to root_path
		else
			render 'new'
		end
			
	end
	
	def edit
		@categories = Category.all.map{ |c| [c.name, c.id] }
	end
	
	def update
		@beer.category_id = params[:category_id]
		if @beer.update(beer_params)
			redirect_to beer_path(@beer)
		else
			render 'edit'
		end
	end
	
	def destroy
		@beer.destroy()
		redirect_to root_path
	end
	
	
	
	private
	
	def beer_params
		params.require(:beer).permit(:name, :description, :brewery, :review, :style, :abv, :category_id, :beer_image)
	end
	
	def find_beer
		@beer = Beer.find(params[:id])
	end
	
end

OneHundredBrews/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	before_action :find_beer
	before_action :find_review, only: [:edit, :update, :destroy]

	def new
		@review = Review.new
	end
	
	def create
		@review = Review.new(review_params)
		@review.beer_id = @beer.id
		@review.user_id = current_user.id
		
		if @review.save
			redirect_to beer_path(@beer)
		else
			render 'new'
		end	
	end
	
	def edit
	end
	
	def update
		if @review.update(review_params)
			redirect_to beer_path(@beer)
		else
			render 'edit'
		end
	end
	
	def destroy
		@review.destroy
		redirect_to beer_path(@beer)
	end
	
	private
	
	def review_params
		params.require(:review).permit(:rating, :comment)
	end
	
	def find_beer
		@beer = Beer.find(params[:beer_id])
	end
	
	def find_review
		@review = Review.find(params[:id])
	end
	
end

OneHundredBrews/app/helpers/application_helper.rb
module ApplicationHelper
end

OneHundredBrews/app/helpers/beers_helper.rb
module BeersHelper
end

OneHundredBrews/app/helpers/reviews_helper.rb
module ReviewsHelper
end

OneHundredBrews/app/views/beers/_form.html.erb
<%= simple_form_for @beer, :html => {:multipart => true} do |f| %>
	<%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select a style") %>
	<%= f.file_field :beer_image %>
	<%= f.input :name, label: "Beer Name:" %>
	<%= f.input :brewery %>
	<%= f.input :description %>
	<%= f.input :review %>
	<%= f.input :style %>
	<%= f.input :abv %>
	<%= f.button :submit %>
<% end %>

OneHundredBrews/app/views/beers/edit.html.erb
<h1>Edit Beer</h1>

<%= simple_form_for @beer, :html => {:multipart => true} do |f| %>
	<%= f.select :category_id, @categories %>
	<%= f.file_field :beer_image %>
	<%= f.input :name, label: "Beer Name:" %>
	<%= f.input :brewery %>
	<%= f.input :description %>
	<%= f.input :review %>
	<%= f.input :style %>
	<%= f.input :abv %>
	<%= f.button :submit %>
<% end %>

OneHundredBrews/app/views/beers/index.html.erb
<h1 class="current-category"><%= params[:category] %></h1>

<% if @beers.count == 0 %>
	<h2>There are no beers currently in this category</h2>
<% else %>

	<div class="row">
		<%- @beers.each do |f| %>
		<div class="col-md-3">
			<a href="/beers/<%= f.id %>" >
				<%= image_tag f.beer_image.url(:beer_index), class: "beer" %>
			</a>
		</div>
		<% end %>
	</div>
	
	
	
<% end %>

OneHundredBrews/app/views/beers/new.html.erb
<h1>new beer</h1>
<%= render 'form' %>

OneHundredBrews/app/views/beers/show.html.erb
<div class="row">
	<div class="col-md-4">
		<%= image_tag @beer.beer_image.url(:beer_show), class: "beer_show" %>
	</div>
	
	<div class="col-md-8">
		<h1><%= @beer.brewery %></h1>
		<h2><%= @beer.name %></h2>
		<p><%= @beer.review %></p>
	</div>
</div>	

<div class="row">
	<div class = "col-md-4">
		<%= render @beer.reviews %>
			<%= link_to "back", root_path %>
	</div>
	
	<div class = "col-md-4">
		<% if user_signed_in? %>
			<%= link_to "Add Review", new_beer_review_path(@beer) %>
			<% if @beer.user_id == current_user.id %>
				<%= link_to "Edit", edit_beer_path(@beer) %>
				<%= link_to "Delete", beer_path(@beer), method: :delete, data: { confirm: "Are you sure?"} %>
			<% end %>
		<% end %>
	</div>
	
</div>

	
<div class = "row">		
Test
</div>

OneHundredBrews/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OneHundredBrews</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<nav class = "navbar navbar-default">
		<div class = "container">
			<div class="navbar-header">
				<%= link_to "One Hundred Brews", root_path, class: "navbar-brand" %>
			</div>
			<ul class="nav navbar-nav">
				<li><%= link_to "Sign Up", new_user_registration_path %></li>
				
				<% if user_signed_in? %>
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% else %>
					<li><%= link_to "Log In", new_user_session_path %></li>
				<% end %>
			</ul>
			<ul class = "nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class = "dropdown-toggle" data-toggle="dropdown" role = "button" aria-expanded="false">Categories <span class="caret"></span></a>
					<ul class="dropdown-menu" role = "menu">
						<% Category.all.each do |cat| %>
							<li class="<%= 'active' if params[:category] == cat.name %>">
								<%= link_to cat.name, beers_path(category: cat.name), class: "link" %>
							</li>
						<% end %>
					</ul>
				
				</li>
				
				
				<% if user_signed_in? %>
					<li><%= link_to "Add Beer", new_beer_path %></li>
				<% end %>
			</ul>
			
			
			
		</div>
	</nav>
	
	
	
	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	
	  
	  
	  
	  
	  
	<div class = "container">
		<%= yield %>
    </div>
  </body>
</html>

OneHundredBrews/app/views/reviews/_form.html.erb
<%= simple_form_for([@beer, @beer.reviews.build]) do |f| %>
<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

OneHundredBrews/app/views/reviews/_review.html.erb
<p><%= review.rating %></p>
<p><%= review.comment %></p>

<% if user_signed_in? %>
	<% if review.user_id == current_user.id %>
		<%= link_to "Edit", edit_beer_review_path(review.beer, review) %>
		<%= link_to "Delete", beer_review_path(review.beer, review), method: :delete, data: {confirm: "Are you sure?" } %>
	<% end %>
<% end %>

OneHundredBrews/app/views/reviews/edit.html.erb
<h1>Edit Review</h1>
<%= simple_form_for([@beer, @review]) do |f| %>
<%= f.input :rating %>
<%= f.input :comment %>
<%= f.button :submit %>
<% end %>

OneHundredBrews/app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>